name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set medium env
      uses: allenevans/set-env@v1.0.0
      with:
        MEDIUM_USERNAME: 'kajornsakp'
        
    - name: Build & Deploy Jekyll
      uses: helaili/jekyll-action@2.0.0
